trigger:
- develop

pool:
  vmImage: ubuntu-latest

stages:

- stage: Develop

  variables:
  - group: Develop

  jobs:      

  - job: Validate

    steps:

    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(SubscriptionId)
        ScriptPath: $(Build.SourcesDirectory)/deploy.ps1
        ScriptArguments: -Prefix $(Prefix)
        azurePowerShellVersion: LatestVersion
