trigger:
- develop

pool:
  vmImage: ubuntu-latest

stages:

- stage: Develop
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')

  variables:
  - group: Develop

  jobs:      

  - job: DevelopValidate

    steps:

    - script: az --version

    - script: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge

    - task: AzureCLI@2
      displayName: Validate
      inputs:
        azureSubscription: $(SubscriptionId)
        scriptType: pscore
        scriptPath: $(Build.SourcesDirectory)/validate.ps1
        arguments:
          -Prefix $(Prefix) `
          -TemplateFile $(Build.SourcesDirectory)/deploy.bicep
    
  - job: DevelopWaitingApproval
    dependsOn: DevelopValidate
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days

    steps:

    - task: ManualValidation@0
      displayName: WaitingApproval
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          maruma@microsoft.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
   
  - deployment: DevelopDeploy
    dependsOn: DevelopWaitingApproval
    environment: Develop
    strategy:
      runOnce:
        deploy:
      
          steps:
                
          - checkout: self 
        
          - task: AzureCLI@2
            displayName: Deploy
            inputs:
              azureSubscription: $(SubscriptionId)
              scriptType: pscore
              scriptPath: $(Build.SourcesDirectory)/deploy.ps1
              arguments:
                -Prefix $(Prefix) `
                -TemplateFile $(Build.SourcesDirectory)/deploy.bicep

- stage: Staging
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')

  variables:
  - group: Staging

  jobs:      

  - job: StagingValidate

    steps:

    - script: az --version

    - script: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge

    - task: AzureCLI@2
      displayName: StagingValidate
      inputs:
        azureSubscription: $(SubscriptionId)
        scriptType: pscore
        scriptPath: $(Build.SourcesDirectory)/validate.ps1
        arguments:
          -Prefix $(Prefix) `
          -TemplateFile $(Build.SourcesDirectory)/deploy.bicep
    
  - job: StagingWaitingApproval
    dependsOn: StagingValidate
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days

    steps:

    - task: ManualValidation@0
      displayName: StagingWaitingApproval
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          maruma@microsoft.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
   
  - deployment: StagingDeploy
    dependsOn: StagingWaitingApproval
    environment: Staging
    strategy:
      runOnce:
        deploy:
      
          steps:
                
          - checkout: self 
        
          - task: AzureCLI@2
            displayName: Deploy
            inputs:
              azureSubscription: $(SubscriptionId)
              scriptType: pscore
              scriptPath: $(Build.SourcesDirectory)/deploy.ps1
              arguments:
                -Prefix $(Prefix) `
                -TemplateFile $(Build.SourcesDirectory)/deploy.bicep
