trigger:
- develop

pool:
  vmImage: ubuntu-latest

stages:

- stage: Develop
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')

  variables:
  - group: Develop

  jobs:      

  - job: Validate

    steps:

    - script: az --version

    - script: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge

    - task: AzureCLI@2
      displayName: Validate
      inputs:
        azureSubscription: $(SubscriptionId)
        scriptType: pscore
        scriptPath: $(Build.DefaultWorkingDirectory)/validate.ps1
        arguments:
          -Prefix $(Prefix) `
          -TemplateFile $(System.DefaultWorkingDirectory)/deploy.bicep
    
  - job: WaitingApproval
    dependsOn: Validate
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days

    steps:

    - task: ManualValidation@0
      displayName: WaitingApproval
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          maruma@microsoft.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
   
  - deployment: Deploy
    dependsOn: WaitingApproval
    environment: Develop
    strategy:
      runonce:
        deploy:
      
          steps:
                
          - checkout: self 
        
          - task: AzureCLI@2
            displayName: Deploy
            inputs:
              azureSubscription: $(SubscriptionId)
              scriptType: pscore
              scriptPath: $(Build.DefaultWorkingDirectory)/deploy.ps1
              arguments:
                -Prefix $(Prefix) `
                -TemplateFile $(System.DefaultWorkingDirectory)/deploy.bicep
