trigger:
- develop

pool:
  vmImage: ubuntu-latest

stages:

- stage: Develop

  variables:
  - group: Develop

  jobs:      

  - job: Validate

    steps:
    - script: az --version
    - script: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SubscriptionId)
        scriptType: pscore
        scriptPath: $(Build.SourcesDirectory)/deploy.ps1
        arguments:
          -Prefix $(Prefix) `
          -TemplateFile $(System.DefaultWorkingDirectory)/deploy.bicep

    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          maruma@microsoft.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
