trigger:
- develop

pool:
  vmImage: ubuntu-latest

stages:

- stage: Develop

  variables:
  - group: Develop

  jobs:      

  - job: Validate

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SubscriptionId)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az config set auto-upgrade.prompt=no
          az config set auto-upgrade.enable=yes

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SubscriptionId)
        scriptType: pscore
        scriptPath: $(Build.SourcesDirectory)/deploy.ps1
        arguments:
          -Prefix $(Prefix) `
          -TemplateFile $(System.DefaultWorkingDirectory)/deploy.bicep
